import { Product } from "@/types";

export const products: Product[] = [
    {
        id: "1",
        name: "Classic White Tee",
        description: "A premium quality cotton t-shirt that fits perfectly. Breathable and durable fabric.",
        price: 29.99,
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
        category: "Clothing",
        storeId: "demo-store",
        isNew: true,
    },
    {
        id: "2",
        name: "Denim Jacket",
        description: "Vintage style denim jacket with a modern twist. Perfect for layering.",
        price: 89.99,
        image: "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
        category: "Clothing",
        storeId: "demo-store",
    },
    {
        id: "3",
        name: "Running Shoes",
        description: "Lightweight and comfortable running shoes for your daily jog.",
        price: 119.99,
        image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
        category: "Footwear",
        rating: 4.5,
        storeId: "demo-store",
    },
    {
        id: "4",
        name: "Leather Backpack",
        description: "Stylish and functional leather backpack for work or travel.",
        price: 159.99,
        image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
        category: "Accessories",
        storeId: "demo-store",
    },
    {
        id: "5",
        name: "Wireless Headphones",
        description: "Noise-cancelling headphones with superior sound quality.",
        price: 199.99,
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
        category: "Electronics",
        isNew: true,
        storeId: "demo-store",
    },
    {
        id: "6",
        name: "Smart Watch",
        description: "Track your fitness and stay connected with this sleek smart watch.",
        price: 249.99,
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
        category: "Electronics",
        storeId: "demo-store",
    },
];
